version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Stockholm'
    target-branch: 'dev'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
    versioning-strategy: 'increase'
    groups:
      next:
        patterns:
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
        update-types:
          - 'minor'
          - 'patch'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
        update-types:
          - 'minor'
          - 'patch'
      sentry:
        patterns:
          - '@sentry/*'
        update-types:
          - 'minor'
          - 'patch'
      testing:
        patterns:
          - 'jest'
          - 'jest-*'
          - 'ts-jest'
          - '@types/jest'
          - '@testing-library/*'
          - '@playwright/test'
          - 'playwright'
        update-types:
          - 'minor'
          - 'patch'
      lint-and-format:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'prettier'
          - 'prettier-*'
          - '@trivago/*'
          - 'husky'
          - 'lint-staged'
        update-types:
          - 'minor'
          - 'patch'
      types:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: 'dev'
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - 'dependencies'
      - 'github-actions'
    groups:
      actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
