allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@sentry/browser-utils@10.67.0'
  - '@sentry/browser@10.67.0'
  - '@sentry/core@10.67.0'
  - '@sentry/feedback@10.67.0'
  - '@sentry/nextjs@10.67.0'
  - '@sentry/node-core@10.67.0'
  - '@sentry/node@10.67.0'
  - '@sentry/opentelemetry@10.67.0'
  - '@sentry/react@10.67.0'
  - '@sentry/replay-canvas@10.67.0'
  - '@sentry/replay@10.67.0'
  - '@sentry/server-utils@10.67.0'
  - '@sentry/vercel-edge@10.67.0'
  - markdown-to-jsx@9.9.0
  - '@testing-library/jest-dom@7.0.0'
  - '@typescript-eslint/eslint-plugin@8.65.0'
  - '@typescript-eslint/parser@8.65.0'
  - '@typescript-eslint/project-service@8.65.0'
  - '@typescript-eslint/scope-manager@8.65.0'
  - '@typescript-eslint/tsconfig-utils@8.65.0'
  - '@typescript-eslint/type-utils@8.65.0'
  - '@typescript-eslint/types@8.65.0'
  - '@typescript-eslint/typescript-estree@8.65.0'
  - '@typescript-eslint/utils@8.65.0'
  - '@typescript-eslint/visitor-keys@8.65.0'
  - lighthouse@13.4.1
  - postcss@8.5.21
  - prettier@3.9.6
  - sass@1.103.0
  - typescript-eslint@8.65.0
  - enhanced-resolve@5.24.4
  - framer-motion@12.43.0
  - motion-dom@12.43.0
  - motion@12.43.0
  - webpack@5.109.2
