allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lint-staged@17.0.7
  - react-hook-form@7.77.0
  - tinyexec@1.2.4
  - '@types/node@25.9.2'
  - '@types/react@19.2.17'
  - '@sentry-internal/browser-utils@10.57.0'
  - '@sentry-internal/feedback@10.57.0'
  - '@sentry-internal/replay-canvas@10.57.0'
  - '@sentry-internal/replay@10.57.0'
  - '@sentry-internal/server-utils@10.57.0'
  - '@sentry/browser@10.57.0'
  - '@sentry/core@10.57.0'
  - '@sentry/nextjs@10.57.0'
  - '@sentry/node-core@10.57.0'
  - '@sentry/node@10.57.0'
  - '@sentry/opentelemetry@10.57.0'
  - '@sentry/react@10.57.0'
  - '@sentry/vercel-edge@10.57.0'
  - '@typescript-eslint/eslint-plugin@8.61.0'
  - '@typescript-eslint/parser@8.61.0'
  - '@typescript-eslint/project-service@8.61.0'
  - '@typescript-eslint/scope-manager@8.61.0'
  - '@typescript-eslint/tsconfig-utils@8.61.0'
  - '@typescript-eslint/type-utils@8.61.0'
  - '@typescript-eslint/types@8.61.0'
  - '@typescript-eslint/typescript-estree@8.61.0'
  - '@typescript-eslint/utils@8.61.0'
  - '@typescript-eslint/visitor-keys@8.61.0'
  - prettier@3.8.4
  - typescript-eslint@8.61.0
