export const CRO_DATA = {
  CLICK_NOT_FOUND_BACK_LINK: 'CLICK_NOT_FOUND_BACK_LINK',
  // CV
  CLICK_DOWNLOAD_CV: 'CLICK_DOWNLOAD_CV',
  CLICK_BURGER_MENU_DOWNLOAD_CV: 'CLICK_BURGER_MENU_DOWNLOAD_CV',
  // READ MORE
  CLICK_ABOUT_US_READ_MORE: 'CLICK_ABOUT_US_READ_MORE',
  // HEADER
  CLICK_LOGO: 'CLICK_LOGO',
  CLICK_MAIN_MENU: 'CLICK_MAIN_MENU',
  CLICK_HEADER_MENU: 'CLICK_HEADER_MENU',
  // BURGER MENU
  CLICK_BURGER_MENU: 'CLICK_BURGER_MENU',
  CLICK_TOGGLE_BURGER_MENU: 'CLICK_TOGGLE_BURGER_MENU',
  // CONTACT US
  CLICK_CONTACT_US_LINKS: 'CLICK_CONTACT_US_LINKS',
  CLICK_CONTACT_US_SUBMIT: 'CLICK_CONTACT_US_SUBMIT',
  // PROJECT
  CLICK_PROJECT_ITEM_DEMO_LINK: 'CLICK_PROJECT_ITEM_DEMO_LINK',
  CLICK_PROJECT_ITEM_CODE_LINK: 'CLICK_PROJECT_ITEM_CODE_LINK'
};
