export const CRO_DATA = {
  HOME_PAGE: 'HOME_PAGE',
  NOT_FOUND_LINK: 'NOT_FOUND_LINK',
  DOWNLOAD_CV: 'DOWNLOAD_CV',
  DOWNLOAD_CV_MOBILE: 'DOWNLOAD_CV_MOBILE',
  ABOUT_US_READ_MORE: 'ABOUT_US_READ_MORE',
  HOME_PAGE_MENU: 'HOME_PAGE_MENU',
  HEADER_MENU: 'HEADER_MENU',
  BURGER_MENU: 'BURGER_MENU',
  TOGGLE_BURGER_MENU: 'TOGGLE_BURGER_MENU',
  CONTACT_US_LINKS: 'CONTACT_US_LINKS',
  CONTACT_US_SUBMIT: 'CONTACT_US_SUBMIT',
  PROJECT_ITEM_DEMO_LINK: 'PROJECT_ITEM_DEMO_LINK',
  PROJECT_ITEM_CODE_LINK: 'PROJECT_ITEM_CODE_LINK'
};
