export const ENV = {
  NODE_ENV: process.env.NODE_ENV ?? 'development',

  AI_TOKEN: process.env.NEXT_PUBLIC_AI_TOKEN,
  AI_ENDPOINT: process.env.NEXT_PUBLIC_AI_ENDPOINT,

  NEXT_RUNTIME: process.env.NEXT_RUNTIME,

  ANALYZE_MODE: process.env.NEXT_PUBLIC_ANALYZE_MODE === 'true',

  GOOGLE_ANALYTICS_CODE: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_CODE ?? '',
  GOOGLE_TAG_MANAGER_CODE: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_CODE ?? '',

  GOOGLE_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY ?? '',
  GOOGLE_RECAPTCHA_SECRET_KEY: process.env.NEXT_PUBLIC_GOOGLE_RECAPTCHA_SECRET_KEY ?? '',

  SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  SENTRY_ENABLED: process.env.NEXT_PUBLIC_SENTRY_ENABLED === 'true'
} as const;
