import Markdown, { RuleType } from 'markdown-to-jsx';
import { redirect } from 'next/navigation';
import type { Metadata } from 'next';
import Script from 'next/script';
import { clsx } from 'clsx';
import React from 'react';

import { ClientCodeLoader, CodeBlock, PageHeader } from '@/shared/components';
import { getPostContent } from '@/shared/helpers/posts/get-post-content';
import type { Post, PostMetadata } from '@/shared/types/post';
import { getPosts } from '@/shared/helpers/posts/get-posts';
import { ContentContainer } from '@/layout/components';
import { ROUTES } from '@/shared/constants';
import { PERSONAL_DATA } from '@/data';

const SITE_URL = PERSONAL_DATA.url.replace(/\/$/, '');

function buildBlogPostingJsonLd(post: Post): string {
  const postUrl = `${SITE_URL}/posts/${post.id}/`;
  const ogImageUrl = `${postUrl}opengraph-image`;

  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    inLanguage: 'en',
    url: postUrl,
    mainEntityOfPage: { '@type': 'WebPage', '@id': postUrl },
    datePublished: new Date(post.date).toISOString(),
    dateModified: new Date(post.date).toISOString(),
    author: {
      '@type': 'Person',
      name: post.author || PERSONAL_DATA.fullName,
      url: PERSONAL_DATA.url
    },
    publisher: {
      '@type': 'Person',
      name: PERSONAL_DATA.fullName,
      url: PERSONAL_DATA.url
    },
    articleSection: post.category,
    keywords: post.tags?.join(', '),
    image: [ogImageUrl]
  });
}

import {
  PostCard,
  BackToPostButton,
  PostReadTime,
  PostCategory,
  PostAuthor,
  PostShare,
  PostTags,
  PostDate
} from './components';

import styles from './post-detail-page.module.scss';

interface Props {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id: postId } = await params;
  const post: Post | null = getPostContent(Number(postId));

  if (!post) {
    return {
      title: 'Post Not Found',
      description: PERSONAL_DATA.pageDescription
    };
  }

  // The dynamic OG image is generated by `opengraph-image.tsx` in this route;
  // Next.js wires it into `openGraph.images` automatically when present.
  return {
    title: post.title,
    description: post.description,
    alternates: { canonical: `/posts/${post.id}/` },
    openGraph: {
      type: 'article',
      title: post.title,
      description: post.description,
      url: `/posts/${post.id}/`,
      publishedTime: new Date(post.date).toISOString(),
      tags: post.tags,
      authors: [PERSONAL_DATA.fullName]
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.description
    }
  };
}

export async function PostDetailPage({ params }: Props) {
  const { id: postId } = await params;
  const post: Post | null = getPostContent(Number(postId));

  if (!post) {
    redirect(ROUTES.POSTS);
  }

  const { data: sameCategoryPosts = [] } = getPosts({ category: post.category });
  const recommendedPosts = sameCategoryPosts
    .filter(({ id }) => id !== Number(postId))
    .slice(0, 3);

  return (
    <ContentContainer animationName="fadeIn">
      <Script
        id={`blog-post-${post.id}-jsonld`}
        type="application/ld+json"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{ __html: buildBlogPostingJsonLd(post) }}
      />
      <PageHeader title={post.title} className="mb-12" />

      <div className="mb-4 flex gap-2 justify-between items-center border-b border-slate-300/40 pb-3 max-md:flex-col max-md:items-start">
        <div className="flex gap-5 max-md:flex-wrap max-md:gap-2">
          <PostAuthor author={post.author} />
          <PostCategory showLabel category={post.category} />
          <PostDate date={post.date} />
          <PostReadTime words={post.content} />
        </div>
        <PostShare postId={post.id} />
      </div>

      <div className="mb-5 [&>*]:mb-3 [&>*:last-child]:mb-0 text-xl">
        <Markdown options={{ createElement: React.createElement, wrapper: null }}>
          {post.description}
        </Markdown>
      </div>

      <div
        className={clsx(
          'text-xl leading-8 [&>*]:mb-3 [&>*:last-child]:mb-4',
          styles['post-detail-page__text']
        )}
      >
        <Markdown
          options={{
            createElement: React.createElement,
            wrapper: null,
            overrides: {
              pre: CodeBlock
            },
            renderRule: (next, node, _renderChildren, state) => {
              if (node.type === RuleType.table) {
                return (
                  <div
                    className={styles['post-detail-page__table-container']}
                    key={state.key}
                  >
                    {next()}
                  </div>
                );
              }

              return next();
            }
          }}
        >
          {post.content}
        </Markdown>
      </div>

      <PostTags postId={post.id} tags={post.tags} />

      <div className="my-10 flex items-center justify-between border-t border-slate-300/40 pt-4">
        <BackToPostButton />
        <PostDate date={post.date} />
      </div>

      {recommendedPosts.length > 0 ? (
        <div className="flex overflow-x-auto gap-4 mb-6 max-lg:flex-col">
          {recommendedPosts.map((post: PostMetadata) => (
            <PostCard key={post.id} data={post} disabledAnimation />
          ))}
        </div>
      ) : null}

      <ClientCodeLoader />
    </ContentContainer>
  );
}
