#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '- Checking your Typescript code ...'
pnpm run check-types ||
(
    echo '❌ Typescript Check Failed.';
    false;
)

echo '- Running your tests ...'
pnpm test ||
(
    echo '❌ Your Tests Failed.';
    false;
)

echo '- Checking your code ...'
pnpm lint-staged
